version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /.dive-preview
    groups:
      react:
        patterns: [react, react-dom]
      motherduck-arrow:
        patterns: ["@motherduck/wasm-client", apache-arrow]
    schedule:
      interval: weekly
