# md-blueprints-environment-model: v1
name: Cleanup Preview Blueprints

permissions:
  contents: read

on:
  pull_request:
    types:
      - closed
  delete:

jobs:
  cleanup:
    uses: motherduckdb/motherduck-blueprints/.github/workflows/reusable_cleanup_preview_blueprints.yaml@__MD_BLUEPRINTS_ACTION_TAG__
